// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pm.Data;

#nullable disable

namespace Pm.Data.Migrations
{
    [DbContext(typeof(PmDbContext))]
    partial class PmDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Pm.Data.Entities.LibraryRoot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AbsPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT")
                        .HasColumnName("abs_path");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("AbsPath")
                        .IsUnique();

                    b.ToTable("library_root", (string)null);
                });

            modelBuilder.Entity("Pm.Data.Entities.PathTagRule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("action");

                    b.Property<long?>("LibraryRootId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("library_root_id");

                    b.Property<string>("Segment")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("segment");

                    b.Property<long?>("TagId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tag_id");

                    b.HasKey("Id");

                    b.HasIndex("TagId");

                    b.HasIndex("LibraryRootId", "Segment")
                        .IsUnique();

                    b.ToTable("path_tag_rule", (string)null);
                });

            modelBuilder.Entity("Pm.Data.Entities.Photo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("CameraModel")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("camera_model");

                    b.Property<string>("Exif")
                        .HasColumnType("TEXT")
                        .HasColumnName("exif");

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("file_hash");

                    b.Property<long?>("FileSize")
                        .HasColumnType("INTEGER")
                        .HasColumnName("file_size");

                    b.Property<double?>("GpsLat")
                        .HasColumnType("REAL")
                        .HasColumnName("gps_lat");

                    b.Property<double?>("GpsLon")
                        .HasColumnType("REAL")
                        .HasColumnName("gps_lon");

                    b.Property<int?>("Height")
                        .HasColumnType("INTEGER")
                        .HasColumnName("height");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("imported_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Mime")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("mime");

                    b.Property<DateTimeOffset?>("TakenAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("taken_at");

                    b.Property<int?>("Width")
                        .HasColumnType("INTEGER")
                        .HasColumnName("width");

                    b.HasKey("Id");

                    b.HasIndex("FileHash")
                        .IsUnique();

                    b.HasIndex("TakenAt")
                        .HasDatabaseName("ix_photo_taken");

                    b.ToTable("photo", (string)null);
                });

            modelBuilder.Entity("Pm.Data.Entities.PhotoLocation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("first_seen_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("last_seen_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("LibraryRootId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("library_root_id");

                    b.Property<DateTimeOffset?>("Mtime")
                        .HasColumnType("TEXT")
                        .HasColumnName("mtime");

                    b.Property<long>("PhotoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("photo_id");

                    b.Property<string>("RelPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT")
                        .HasColumnName("rel_path");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("present")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("PhotoId")
                        .HasDatabaseName("ix_loc_photo");

                    b.HasIndex("LibraryRootId", "RelPath")
                        .IsUnique();

                    b.ToTable("photo_location", (string)null);
                });

            modelBuilder.Entity("Pm.Data.Entities.PhotoTag", b =>
                {
                    b.Property<long>("PhotoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("photo_id");

                    b.Property<long>("TagId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tag_id");

                    b.Property<float?>("Confidence")
                        .HasColumnType("REAL")
                        .HasColumnName("confidence");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("source");

                    b.HasKey("PhotoId", "TagId");

                    b.HasIndex("TagId", "PhotoId")
                        .HasDatabaseName("ix_phototag_tag");

                    b.ToTable("photo_tag", (string)null);
                });

            modelBuilder.Entity("Pm.Data.Entities.SavedSearch", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("QueryJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("query_json");

                    b.HasKey("Id");

                    b.ToTable("saved_search", (string)null);
                });

            modelBuilder.Entity("Pm.Data.Entities.Tag", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("manual")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("tag", (string)null);
                });

            modelBuilder.Entity("Pm.Data.Entities.TagRelation", b =>
                {
                    b.Property<long>("ParentTagId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("parent_tag_id");

                    b.Property<long>("ChildTagId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("child_tag_id");

                    b.HasKey("ParentTagId", "ChildTagId");

                    b.HasIndex("ChildTagId")
                        .HasDatabaseName("ix_tagrel_child");

                    b.ToTable("tag_relation", null, t =>
                        {
                            t.HasCheckConstraint("ck_tagrel_no_self", "parent_tag_id <> child_tag_id");
                        });
                });

            modelBuilder.Entity("Pm.Data.Entities.TaggingJob", b =>
                {
                    b.Property<long>("PhotoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("photo_id");

                    b.Property<int>("Attempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset>("EnqueuedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("enqueued_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("State")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("pending")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("PhotoId");

                    b.HasIndex("State")
                        .HasDatabaseName("ix_job_state")
                        .HasFilter("state IN ('pending','error')");

                    b.ToTable("tagging_job", (string)null);
                });

            modelBuilder.Entity("Pm.Data.Entities.PathTagRule", b =>
                {
                    b.HasOne("Pm.Data.Entities.LibraryRoot", null)
                        .WithMany()
                        .HasForeignKey("LibraryRootId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Pm.Data.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId");
                });

            modelBuilder.Entity("Pm.Data.Entities.PhotoLocation", b =>
                {
                    b.HasOne("Pm.Data.Entities.LibraryRoot", "LibraryRoot")
                        .WithMany("Locations")
                        .HasForeignKey("LibraryRootId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pm.Data.Entities.Photo", "Photo")
                        .WithMany("Locations")
                        .HasForeignKey("PhotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LibraryRoot");

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("Pm.Data.Entities.PhotoTag", b =>
                {
                    b.HasOne("Pm.Data.Entities.Photo", null)
                        .WithMany("Tags")
                        .HasForeignKey("PhotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pm.Data.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pm.Data.Entities.TagRelation", b =>
                {
                    b.HasOne("Pm.Data.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("ChildTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pm.Data.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("ParentTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pm.Data.Entities.TaggingJob", b =>
                {
                    b.HasOne("Pm.Data.Entities.Photo", null)
                        .WithMany()
                        .HasForeignKey("PhotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pm.Data.Entities.LibraryRoot", b =>
                {
                    b.Navigation("Locations");
                });

            modelBuilder.Entity("Pm.Data.Entities.Photo", b =>
                {
                    b.Navigation("Locations");

                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
